import type {SyncPayload} from './types'
import {decryptSyncPayload,encryptSyncPayload} from './sync'
const endpoint=String(import.meta.env.VITE_SUSH_SYNC_ENDPOINT||'').replace(/\/$/,'')
export function syncAvailable(){try{return new URL(endpoint).origin==='https://sync.sush.dev'}catch{return false}}
function token(v:string){if(v.length<16||v.length>8192||/[\r\n]/.test(v))throw new Error('Invalid Sush account token.')}
async function request(path:string,init:RequestInit){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15_000);try{return await fetch(endpoint+path,{...init,signal:controller.signal})}finally{clearTimeout(timer)}}
export async function pushEncryptedSync(payload:SyncPayload,pass:string,account:string){if(!syncAvailable())throw new Error('Sush account sync is not configured for this build.');token(account);const r=await request('/v1/air/sync',{method:'PUT',headers:{'content-type':'application/json',authorization:`Bearer ${account}`},body:JSON.stringify({version:1,encrypted:await encryptSyncPayload(payload,pass)})});if(!r.ok)throw new Error(`Sync upload failed (${r.status}).`)}
export async function pullEncryptedSync(pass:string,account:string){if(!syncAvailable())throw new Error('Sush account sync is not configured for this build.');token(account);const r=await request('/v1/air/sync',{headers:{authorization:`Bearer ${account}`}});if(!r.ok)throw new Error(`Sync download failed (${r.status}).`);const body=await r.json() as{encrypted?:string};if(!body.encrypted)throw new Error('The account has no Air sync bundle.');return decryptSyncPayload(body.encrypted,pass)}
export async function fetchAccountEntitlement(account:string){if(!syncAvailable())return null;token(account);const r=await request('/v1/air/entitlement',{headers:{authorization:`Bearer ${account}`}});if(r.status===204||r.status===404)return null;if(!r.ok)throw new Error(`Entitlement check failed (${r.status}).`);return((await r.json())as{entitlementToken?:string}).entitlementToken||null}
