import type { AirSession, ShellProfile, WorkspaceCapsule } from './types'
import { isAbsoluteWorkspacePath, safeHistoryEntry } from './security'
import { validateCapsule } from './capsules'
const P='sush-air:v1:'
function read<T>(key:string,fallback:T):T{try{const v=localStorage.getItem(P+key);return v?JSON.parse(v) as T:fallback}catch{return fallback}}
function write(key:string,value:unknown){try{localStorage.setItem(P+key,JSON.stringify(value))}catch{}}
export function loadProfiles(platform:string):ShellProfile[]{const defaults:ShellProfile[]=platform==='macos'?[{id:'zsh',label:'zsh',shell:'zsh',theme:'air'},{id:'bash',label:'Bash',shell:'bash',theme:'mono'}]:platform==='windows'?[{id:'powershell',label:'PowerShell',shell:'powershell',theme:'air'},{id:'cmd',label:'Command Prompt',shell:'cmd',theme:'mono'}]:[{id:'bash',label:'Bash',shell:'bash',theme:'air'}];const saved=read<ShellProfile[]>('profiles',defaults),allowed=platform==='windows'?new Set(['powershell','pwsh','cmd']):new Set(['zsh','bash','sh']);const accepted=Array.isArray(saved)?saved.filter(x=>x&&/^[A-Za-z0-9_-]{1,40}$/.test(String(x.id))&&allowed.has(x.shell)&&['air','mono','ocean'].includes(x.theme)).map(x=>({...x,label:String(x.label||x.shell).slice(0,60)})).slice(0,20):[];return accepted.length?accepted:defaults}
function session(value:unknown):AirSession|null{if(!value||typeof value!=='object'||Array.isArray(value))return null;const x=value as Partial<AirSession>,cwd=String(x.cwd||''),shell=String(x.shell||'');if(!/^[A-Za-z0-9_-]{8,80}$/.test(String(x.id||''))||!isAbsoluteWorkspacePath(cwd)||!['zsh','bash','sh','powershell','pwsh','cmd'].includes(shell)||!/^[A-Za-z0-9_-]{1,40}$/.test(String(x.profileId||'')))return null;return{id:String(x.id),label:String(x.label||'Terminal').slice(0,80),cwd,shell,profileId:String(x.profileId),scratch:x.scratch===true,privacy:x.privacy===true,createdAt:Number.isFinite(x.createdAt)?Number(x.createdAt):Date.now(),lastActiveAt:Number.isFinite(x.lastActiveAt)?Number(x.lastActiveAt):Date.now()}}
export function loadCheckpoint(){const x=read<AirSession[]>('checkpoint',[]);return Array.isArray(x)?x.map(session).filter((v):v is AirSession=>!!v).filter(v=>!v.scratch&&!v.privacy).sort((a,b)=>b.lastActiveAt-a.lastActiveAt).slice(0,12):[]}
export function saveCheckpoint(values:AirSession[]){write('checkpoint',values.filter(v=>!v.scratch&&!v.privacy).map(({agent:_agent,...v})=>v).slice(0,12))}
export function loadCapsules(){const x=read<WorkspaceCapsule[]>('capsules',[]);return Array.isArray(x)?x.flatMap(v=>{try{return[validateCapsule(v)]}catch{return[]}}).slice(0,100):[]}
export function saveCapsules(v:WorkspaceCapsule[]){write('capsules',v.slice(0,100))}
export function loadHistory(){const x=read<unknown[]>('history',[]);return Array.isArray(x)?x.map(v=>safeHistoryEntry(String(v??''))).filter((v):v is string=>v!==null).slice(-500):[]}
export function appendHistory(command:string){const v=safeHistoryEntry(command);if(!v)return;const h=loadHistory();if(h.at(-1)!==v)h.push(v);write('history',h.slice(-500))}
export function readDropUsage(day=new Date().toISOString().slice(0,10)){const v=read<unknown>('drop-usage',null);if(!v||typeof v!=='object')return 0;const x=v as{day?:unknown;count?:unknown},count=Number(x.count);return x.day===day&&Number.isFinite(count)?Math.max(0,Math.floor(count)):0}
export function incrementDropUsage(day=new Date().toISOString().slice(0,10)){const count=readDropUsage(day)+1;write('drop-usage',{day,count});return count}
