import type { SyncPayload,SyncPreferences,WorkspaceCapsule } from './types'
import {containsLikelySecret,isSensitiveCommand} from './security'
import {validateCapsule} from './capsules'
const encoder=new TextEncoder(),decoder=new TextDecoder()
const b64=(bytes:Uint8Array)=>{let s='';for(const x of bytes)s+=String.fromCharCode(x);return btoa(s)}
const bytes=(v:string):Uint8Array<ArrayBuffer>=>{const s=atob(v),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a}
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)
function sanitizeObject(v:Record<string,unknown>){const blocked=/secret|token|password|history|scrollback|oauth|environment|env/i;return Object.fromEntries(Object.entries(v).filter(([k,x])=>!blocked.test(k)&&!containsLikelySecret(JSON.stringify(x))).slice(0,100))}
export function buildSyncPayload(input:{preferences?:Record<string,unknown>;themes?:unknown[];recipes?:Array<{id:string;label:string;command:string}>;capsules?:WorkspaceCapsule[];agentPreferences?:Record<string,string>},selected:SyncPreferences):SyncPayload{const p:SyncPayload={version:1,createdAt:Date.now()};if(selected.themes){p.preferences=sanitizeObject(input.preferences||{});p.themes=Array.isArray(input.themes)?structuredClone(input.themes).slice(0,50):[]}if(selected.recipes)p.recipes=(input.recipes||[]).filter(x=>x&&!isSensitiveCommand(x.command)).map(x=>({id:String(x.id).slice(0,64),label:String(x.label).slice(0,80),command:String(x.command).slice(0,1000)})).slice(0,200);if(selected.capsules)p.capsules=(input.capsules||[]).flatMap(x=>{try{const v=validateCapsule(x);return containsLikelySecret(JSON.stringify(v))?[]:[v]}catch{return[]}}).slice(0,100);if(selected.agentPreferences)p.agentPreferences=Object.fromEntries(Object.entries(input.agentPreferences||{}).filter(([k,v])=>!/secret|token|key|password/i.test(k)&&!containsLikelySecret(v)).slice(0,100));return p}
export function validateSyncPayload(v:unknown):SyncPayload{if(!object(v)||v.version!==1)throw new Error('Invalid sync payload.');return buildSyncPayload({preferences:object(v.preferences)?v.preferences:undefined,themes:Array.isArray(v.themes)?v.themes:undefined,recipes:Array.isArray(v.recipes)?v.recipes.flatMap(x=>object(x)?[{id:String(x.id||''),label:String(x.label||''),command:String(x.command||'')}]:[]):undefined,capsules:Array.isArray(v.capsules)?v.capsules as WorkspaceCapsule[]:undefined,agentPreferences:object(v.agentPreferences)?Object.fromEntries(Object.entries(v.agentPreferences).map(([k,x])=>[k,String(x)])):undefined},{themes:!!(v.preferences||v.themes),recipes:!!v.recipes,capsules:!!v.capsules,agentPreferences:!!v.agentPreferences})}
async function key(pass:string,salt:Uint8Array<ArrayBuffer>){const material=await crypto.subtle.importKey('raw',encoder.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:310_000},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function passphrase(v:string){if(v.length<12)throw new Error('Sync passphrase must contain at least 12 characters.');if(v.length>1024)throw new Error('Sync passphrase must contain at most 1,024 characters.')}
export async function encryptSyncPayload(payload:SyncPayload,pass:string){passphrase(pass);const plain=JSON.stringify(validateSyncPayload(payload));if(plain.length>1024*1024)throw new Error('Sync payload exceeds the 1 MB limit.');const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(pass,salt),encoder.encode(plain)));return JSON.stringify({version:1,kdf:'PBKDF2-SHA256-310000',cipher:'AES-256-GCM',salt:b64(salt),iv:b64(iv),ciphertext:b64(cipher)})}
export async function decryptSyncPayload(envelope:string,pass:string){passphrase(pass);if(envelope.length>2*1024*1024)throw new Error('Sync bundle exceeds the 2 MB limit.');const p=JSON.parse(envelope) as Record<string,unknown>;if(p.version!==1||p.kdf!=='PBKDF2-SHA256-310000'||p.cipher!=='AES-256-GCM')throw new Error('Unsupported sync bundle.');const salt=bytes(String(p.salt||'')),iv=bytes(String(p.iv||'')),cipher=bytes(String(p.ciphertext||''));if(salt.length!==16||iv.length!==12||cipher.length<16||cipher.length>1024*1024+64)throw new Error('Invalid sync bundle dimensions.');return validateSyncPayload(JSON.parse(decoder.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},await key(pass,salt),cipher))))}
